/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TriviaGame__factory } from "./TriviaGame__factory";
export { TriviaToken__factory } from "./TriviaToken__factory";
